/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Sharliz-Portfolio-v4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Sharliz-Portfolio-v4.glb')
  console.log(nodes);
  

  const newMaterials = convertMaterialsToBasic(materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Ground} position={[10.016, 0, 8.976]} scale={0.665} />
      <mesh geometry={nodes.BaseRoom.geometry} material={newMaterials.BakedTexture} />
      <mesh geometry={nodes.Desk.geometry} material={newMaterials.BakedDesk}>
        <mesh geometry={nodes.구체.geometry} material={newMaterials.STEEL} />
        <mesh geometry={nodes.구체_1.geometry} material={newMaterials.Light} />
      </mesh>
      <mesh geometry={nodes.Lamp.geometry} material={newMaterials.LAmp} />
      <mesh geometry={nodes.Rug.geometry} material={newMaterials.Rug} />
    </group>
  )
}

useGLTF.preload('/models/Sharliz-Portfolio-v4.glb')
